### ISSUE TITLE
No input file found

### ISSUE THREAD

**Issue by notknowchild** [AdamSpannbauer/python_video_stab#109]
Describe the bug
FileNotFoundError(f'{input_path} does not exist')

Provide version info
Python 3.5.6
cv2.version '4.2.0'
vidstab version 1.7.3
OS:Windows10

I think this project is very interesting, but I don’t know how to run it. I just entered a line in the jupyter notebook: from vidstab import Vidstab, I got this error, I don’t know where this input_path should be put.

**Comment by AdamSpannbauer** [comment]
To confirm, you're saying the only line of code you ran was `from vidstab import Vidstab` and you received the above error?

**Comment by notknowchild** [comment]
![image](https://user-images.githubusercontent.com/44050351/85124999-6f771800-b25d-11ea-8f09-84b751bc0444.png)
Yes

**Comment by AdamSpannbauer** [comment]
The class name is `VidStab` rather than `Vidstab`.  However, I'm not sure that correcting the import statement (to `from vidstab import VidStab`) will fix the issue.  I'm surprised that you didn't receive an `ImportError` as instead of the one you're showing (i.e. when I run your line of code: `ImportError: cannot import name 'Vidstab' from 'vidstab'`).  So there is something else going on that I'm not sure how to diagnose.

You might try reinstalling, restarting kernel, all the other go-to "turn it off and back on" techniques.

I am not an anaconda user.  If your issue persists, I can try installing anaconda and seeing if I'm able to recreate your error that way.

**Comment by notknowchild** [comment]
I used： from vidstab import VidStab and still showed the above error. I reinstalled and used python3.5 and python2.7 to run, and displayed such information in VidStab.py. 
![image](https://user-images.githubusercontent.com/44050351/85130033-be757b00-b266-11ea-94b0-a302df568a44.png)
What method did you use to run this code and What is the version of python?

**Comment by AdamSpannbauer** [comment]
Oh I just realized the issue. You’re receiving a syntax error because f strings were introduced in python 3.6 and your version of python is 3.5.3. Try using >=3.6

I’ll update the package to either avoid f strings or to be more explicit about its version requirements

**Comment by notknowchild** [comment]
Thank you, thank you very much. I ran this code using python3.7 and this error disappeared.

**Comment by AdamSpannbauer** [comment]
The short-term solution was to put a minimum python version in `setup.py`.  Potentially revisit and consider older versions (but unlikely).
