### ISSUE TITLE
I  get (No module named 'imutils') error

### ISSUE THREAD

**Issue by Rothax** [AdamSpannbauer/python_video_stab#118]
I didnt changed anything . Only installed necessary modules, of course it is include imtulis module but it gives this error
![error1](https://user-images.githubusercontent.com/54594660/105900062-98019480-602c-11eb-886d-5eb99c26900a.png)

**Comment by AdamSpannbauer** [comment]
How did you install `vidstab`?  It looks like your working directory is the vidstab directory, and I'm questioning whether anything was installed or if you just cloned the repo and ran the code.

Install with either:
* To install from PyPi use: `pip install vidstab` (or `pip install vidstab[cv2]` if you don't already have opencv installed)
* To install from the repo you cloned run: `pip install .` in the repo's directory

**Comment by Rothax** [comment]
I used "pip install vidstab[cv2]" for install vidstab

**Comment by AdamSpannbauer** [comment]
Are you sure that you installed in the same environment that your code is running in?  Can you prove that `vidstab` is installed by running something like `pip list` or `pip list | grep vid`.  Or perhaps by doing `python` -> `import vidstab` (not in the vidstab directory).

**Comment by AdamSpannbauer** [comment]
So there is definitely some disconnect between the python process running the code and that list of installed packages since we can see `imutils` in the list.

To try and ensure you're using the appropriate pip + python you can try and install with:

```
python3 -m pip install vidstab[cv2]
```

You might have your `pip` for python 2 and `pip3` for managing python 3 packages (not for sure of course, but a possibility).
